#requires -Version 1
#
# Module manifest for module 'PowerWorks'
#
# Generated by: Robert Gouge
#
# Generated on: 3/26/2017
#

@{
    RootModule        = 'PowerWorks.psm1'
    ModuleVersion     = '0.0.13.44'
    GUID              = '92f21958-43c1-437f-9692-0725cc02405f'
    Author            = 'Robert Gouge'
    CompanyName       = 'Unknown'
    Copyright         = '(c) 2017 Robert Gouge. All rights reserved.'
    Description       = 'A collection of cmdlets and classes to provide enchanced tools for SysAdmins'
    NestedModules     = 'Public\Test-Port.ps1'
    FunctionsToExport = @('Test-Port')
    CmdletsToExport   = @()
    VariablesToExport = '*'
    AliasesToExport   = @()
    PrivateData       = @{
        PSData = @{
            Tags         = @('SysAdmin', 'Networking', 'System', 'Administration', 'Tools')
            LicenseUri   = 'https://github.com/RobertCGouge/PowerWorks/blob/master/LICENSE'
            ProjectUri   = 'https://github.com/RobertCGouge/PowerWorks'
            ReleaseNotes = '# Version 0.0.13.44 (2017-03-28)
         
## Notes

First release with functionality

## Functtions

### Test-Port

* Added support for the Verbose switch.
* Added support for either using an IPv4 address or computer name
* Added logic to allow for use'
        }
    }
}














































